version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: MochaDB
    restart: unless-stopped
    environment:
      POSTGRES_DB: mocha
      POSTGRES_USER: mocha_user
      POSTGRES_PASSWORD: mocha_pass
    ports:
      - "5433:5432"  # Port 5433 sur votre machine -> 5432 dans le container
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database_schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mocha_user -d mocha"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
