name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
    sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
    shelf: ^1.4.0
    shelf_router: ^1.1.0
    postgres: ^3.0.0
    bcrypt: ^1.1.3
    dart_jsonwebtoken: ^2.14.0
    dotenv: ^4.0.1
    http: ^1.2.1
    flutter_secure_storage: ^9.0.0

dev_dependencies:
    lints: ^6.0.0
    test: ^1.25.6
